### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by TheoPannetier** [tresinformal/basketball#1]
By default, @martprenger and I have chosen a GNU 3.0 Public license, but may want to decide as a group what license to use for the game. I suggest the three classic options:

1. GNU 3.0
2. MIT
3. Creative Commons

**Comment by TheoPannetier** [comment]
Let's talk about it with everyone and vote October 18th

**Comment by richelbilderbeek** [comment]
Next week, Oct 18th, @TheoPannetier will present this and the options in max 15 minutes. We vote by :+1: (i.e. one can vote on zero, one, more or all options), most :+1:s wins.

**Comment by TheoPannetier** [comment]
Consensus reached, GNU GPL3 wins!
