### ISSUE TITLE
A game has a screen size

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/basketball#26]
A game has a screen size (or maybe better: arena size): it determines which coordinates are inside and outside of the screen; it does not need to match a monitor's resolution at all.

Allow for this test!

```c++
    const game g;
    get_screen_size(g); // This is all that needs to be accounted for
```

**Comment by TheoPannetier** [comment]
We decided to split get_screen_size() into two functions, get_screen_width() and get_screen_height(), because it is not intuitive what a screen "size" is.

```cpp

  {
    const game g;
    get_screen_width(g);
    get_screen_height(g);
  }

```

**Comment by martprenger** [comment]
this issue is done
