### ISSUE TITLE
A ball has a coordinat that can actually change

### ISSUE THREAD

**Issue by richelbilderbeek** [tresinformal/basketball#36]
Currently, the coordinat of a ball is (3.14, 27.1), as tested in #33. However, it was intended that one can set and get any value. Make this test come true too:

```c++
  // 34
  {
    ball b;
    const double x{2.71};
    b.set_x(x);
    assert(b.get_x() == x)
    const double y{3.14};
    b.set_y(y);
    assert(b.get_y() == y)
  }
```

**Comment by martprenger** [comment]
we can close this one because we compelted #33 in the intended way :)
